services:
  cybercheck:
    image: cybercheck_hu:latest
    container_name: cybercheck
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
      SQLITE_DB_PATH: /data/cybercheck.db
      SEED_DEMO: "true"
      SESSION_COOKIE_SECURE: "false"
    volumes:
      - /share/Container/cybercheck/data:/data
